[package]
name = "rebc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-gen = "0.1"
wasmparser = "0.83"
pretty-hex = "0.2.1"

[lib]
name = "my_rust_lib"
crate-type = ["staticlib"]
